### ISSUE TITLE
Error from react-select in 0.3.14

### ISSUE THREAD

**Issue by frontyard** [keystonejs/keystone#1730]
I'm gettting this error "Uncaught TypeError: Cannot read property 'length' of undefined", coming from packages.js which is minified and makes it difficult to debug.

I managed to track it to Select.js line 550:
```javascript
loadAsyncOptions (input, state, callback) {
    var thisRequestId = this._currentRequestId = requestId++;
    if (this.props.cacheAsyncResults) {
        for (var i = 0; i <= input.length; i++) {
```
For some reason input is undefined and this block croaks on the for loop.

This is happening on regular Text fields and on Html fields.

Partial stack trace:
```javascript
o.createClass.loadAsyncOptions	@	packages.js:8
o.createClass.componentWillReceiveProps	@	packages.js:8
b.updateComponent	@	packages.js:2
b.receiveComponent	@	packages.js:2
i.receiveComponent	@	packages.js:4
```

**Comment by JedWatson** [comment]
I believe this has been fixed by the update I released yesterday (`keystone@0.3.15`) - please reopen if you can still replicate it on that version :)

**Comment by jorge07** [comment]
I'm on version:
     "keystone": "^0.3.15"
And I still having this issue.

**Comment by jorge07** [comment]
Can someone help me to fix this issue? I spend few hours but I'll need some help...

**Comment by morenoh149** [comment]
@jorge07 what have you tried? have you tried asking in https://gitter.im/keystonejs/keystone ?

**Comment by jorge07** [comment]
@morenoh149 I was trying to fint the origin of this issue but as @frontyard said, it's really difficult to debug. I'm not very familiar yet with keystone insternals so that's why I need some help. Thanks I'll ask there.

**Comment by mekanics** [comment]
any news here? 
I'm having the same issue

**Comment by ppiekarczyk** [comment]
:wave: confirmed that this still is an issue in 0.3.17 :)

**Comment by wmertens** [comment]
So is this a bug in react-select or in how keystone uses it?

**Comment by sean-stanley** [comment]
+1 I am having this issue in 0.3.17 node version 0.10.43. This issue is happening on boolean checkboxes as well.

**Comment by sean-stanley** [comment]
I resolved by downgrading to 0.3.13 in case that is relevant to anyone else.

**Comment by btippett** [comment]
@JedWatson I am still seeing this issue on Cloudinary Image fields in Keystone JS admin interface v0.3.21.

I see that the underlying issue in react-select was fixed over in https://github.com/JedWatson/react-select/commit/c3c37214e85bed52640c08d4e711d6a53fc9d31a but in Keystone v0.3.21 the react-select dependency is still ["react-select": "^0.6.12"](https://github.com/keystonejs/keystone/blob/v0.3.21/package.json). NPM is resolving this as `">=0.6.12 <0.7.0"` and so Keystone ends up bundling an old version that still contains the bug.

I see on master, the dependency is now ["react-select": "1.0.0-beta14"]( https://github.com/keystonejs/keystone/blob/master/package.json). If it's not possible to publish that just yet since it's potentially a breaking change could the dependency at least be bumped to `"react-select": "^0.9.1"` until react-select 1.0.0 is ready? It seems that would resolve the issue immediately.

**Comment by peterpme** [comment]
I've been working on upgrading React in keystone to fix this. I closed the branch, but kept it as a reference:

https://github.com/keystonejs/keystone/pull/3182/files
