### ISSUE TITLE
Cannot access `Relationship` fields within Access Control methods

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1856]
The `existingItem` variable passed in to `ImperativeAccess` access control functions does not contain fields with type `Relationship` (or, more correctly; with `.isRelationship === true`).

Example:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: Text }
  }
});
keystone.createList('Post', {
  fields: {
    authors: { type: Relationship, many: true, ref: User }
    viewCount: {
      type: Integer,
      defaultValue: 0,
      access: {
        // Goal: only authors can see the `viewCount`
        // Reality: `existingItem.authors` is `undefined`
        read: ({ authentication: { item }, existingItem }) => !!item && existingItem.authors.includes(item.id),
      }
    }
  }
});
```

Access Control methods cannot return `Promise`s (and cannot be `async`), so it's not possible to leverage something like `keystone.executeQuery()`.

I believe this is a regression.

However, my preference is to reinstate the ability to fetch `Relationship` fields in a more deterministic / declarative way. Perhaps something like I suggested in #1695?

**Comment by jesstelford** [comment]
Now that https://github.com/keystonejs/keystone/pull/2872 is merged, a workaround here is do an asynchronous query for the data you need in your access control function, like so:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: Text }
  }
});
keystone.createList('Post', {
  fields: {
    authors: { type: Relationship, many: true, ref: User },
    viewCount: {
      type: Integer,
      defaultValue: 0,
      access: {
        // Goal: only authors can see the `viewCount`
        // Reality: `existingItem.authors` is `undefined`
        read: async ({ authentication: { item }, existingItem }) => {
          if (!item) {
            return false;
          }
          const { data, errors } = await keystone.query(
            `
              query($postId: ID!, $userId: ID!) {
                Post(where: { id: $postId }) {
                  _authorsMeta(where: { id: $userId }) {
                    count
                  }
                }
              }
            `,
            { variables: { postId: existingItem.id, userId: item.id } }
          );

          if (errors) {
            throw errors;
          }

          return !!data.Post._authorsMeta.count;
        }
      }
    }
  }
});
```

**Comment by timleslie** [comment]
This is now solved with the `context.executeGraphQL` function, which is available to all access control functions.

```
keystone.createList('User', {
  fields: {
    name: { type: Text }
  }
});
keystone.createList('Post', {
  fields: {
    authors: { type: Relationship, many: true, ref: User },
    viewCount: {
      type: Integer,
      defaultValue: 0,
      access: {
        // Goal: only authors can see the `viewCount`
        // Reality: `existingItem.authors` is `undefined`
        read: async ({ authentication: { item }, existingItem, context }) => {
          if (!item) {
            return false;
          }
          const { data, errors } = await context.executeQuery({
            query: `
              query($postId: ID!, $userId: ID!) {
                Post(where: { id: $postId }) {
                  _authorsMeta(where: { id: $userId }) {
                    count
                  }
                }
              }
            `,
            variables: { postId: existingItem.id, userId: item.id }
          });

          if (errors) {
            throw errors;
          }

          return !!data.Post._authorsMeta.count;
        }
      }
    }
  }
});
```

**Comment by borg** [comment]
It seems to me the problem still remains, particularly on a list level, for two reasons, from what I can tell. 
1. If relationships are expanded you can't query access membership lists, not even if they are on the same list.
2. existingItem doesn't exist on list level, and for read, neither does itemId from what I can tell, so how would you query a separate access control list even if you could expand the relationships? Surely including itemId for read access checks is a minor fix?

**Comment by borg** [comment]
I think I have learnt a bit more about how this works. Comment here if it's helpful to someone else. 

So itemId won't be available for general listing queries, like allPosts, but it will be for individual Post queries. So to limit what items are included in the list, the where clause need to filter out inaccessible posts somehow. 

```
...access: {
        // Goal: only show posts if user is follower to author
        //problem, the follows relationship isn't expanded on the user object
        read: async ({itemId, authentication: { item:user }, existingItem, context }) => {

let userFollows = [];

/*
This doesn't work

  for(let c of user.follows){
    userFollows.push(c.id);
  }

*/
//But this does
  let queryString = `query ($userId: ID!) {
    User(where: {id: $userId }) {
      name
      follows{
        id
        name
      }
      followers{
        id
        name
      }
      
    }
  }`;

  try{
    const { data, errors } = await context.executeGraphQL({
      context:context.createContext({ schemaName : 'public', skipAccessControl :true}),
      query: queryString,
      variables: {userId: user.id},
      });

      console.log("user data");
      console.log(data);//relationships don't seem to be available here, but they actually are 
      if(errors){
        l(errors, "user errors");
      }

      for(let c of data.User.follows){
        userFollows.push(c.id);
      }

  }
  catch(err){
    console.log(err);
  }
```
