### ISSUE TITLE
Browser errors while using "Create" in admin web interface

### ISSUE THREAD

**Issue by philmcm** [keystonejs/keystone#1941]
# Bug report
Both Edge and Firefox give (different) error messages when using the "+ Create" button in the admin interface.

## Describe the bug
After starting the Keystone Todo Quickstart, errors are produced when using the "+ Create" button in both Edge and Firefox.

## To Reproduce
Run "npm init keystone-app ks", "npm run dev" and browse to the admin interface.
Open "Todos"
Click "+ Create"
Add new Todo item.
Edge generates the following message on R.H.S. of browser window:  "Unable to get property 'refetch' of undefined or null reference"
Firefox generates the following message on R.H.S. of browser window: "_this.currentObservable.query is Undefined"

NOTE: the addition of the todo works fine, however, the messages should not be generated.

## Expected behaviour

The error messages should not be generated.

## Screenshots
Edge:
<img width="1080" alt="2019-11-09 (1)" src="https://user-images.githubusercontent.com/11898246/68522988-8ee0b680-0306-11ea-9e26-e9d37d0bcfd7.png">
Firefox:
<img width="1080" alt="2019-11-09" src="https://user-images.githubusercontent.com/11898246/68522990-956f2e00-0306-11ea-9b93-15c7f67eab3d.png">

## System information

- OS: Windows 10, Vagrant 2.2.6, hashicorp/bionic64 box (Ubuntu 18.04.3 LTS).
Node JS version 10.17.0
MongoDB version 
- Browser:  Edge and Firefox

**Comment by MadeByMike** [comment]
Confirmed... it doesn't seem to have any negative impact. @jesstelford pinging you because you might have insight.

**Comment by danieljustus32** [comment]
Chrome version 78.0.3904.87 is producing the same `Cannot get property 'refetch' of undefined` error for me as well, only on the first time clicking the "Create" button and only on the first item added to a list.

**Comment by cloud90bk** [comment]
> 
> 
> Confirmed... it doesn't seem to have any negative impact. @jesstelford pinging you because you might have insight.

Any news about this error?

**Comment by Vultraz** [comment]
Tried digging into this. All I can ascertain is it's coming from [here](https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/pages/List/index.js#L101) which is being called from [here](https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/components/CreateItemModal.js#L76) but I can't figure out what's causing it.

**Comment by Vultraz** [comment]
Fixed in #2080

**Comment by cloud90bk** [comment]
Hi, I've updated the node modules but still have the error message. It has been released?
I use this version now:
"@keystonejs/adapter-mongoose": "5.1.3",
"@keystonejs/app-admin-ui": "5.4.0",
"@keystonejs/app-graphql": "5.0.1",
"@keystonejs/app-static": "5.0.0",
"@keystonejs/auth-password": "5.0.1",
"@keystonejs/fields": "6.0.1",
"@keystonejs/file-adapters": "5.2.0",
"@keystonejs/keystone": "5.3.0",

**Comment by Vultraz** [comment]
The fix was just merged today. Hasn't been released yet.
