### ISSUE TITLE
4.0-Beta-1: Updating password generates 500 error

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#3428]
### Steps to reproduce the behavior
Change a user's password and try to save the item.

### Expected behavior
The new password should be saved.

### Actual behavior
An 500 error is generated.

** NOTE: after this is fix please remove the following line from test/e2e/adminUI/tests/group005Fields/testPasswordField.js and make sure the test passes **
```
'@disabled': true,  // TODO: enable after https://github.com/keystonejs/keystone/issues/3428 is fixed
```

**Comment by JedWatson** [comment]
@webteckie I can't reproduce this in the test project... I tried changing a user's password in the Admin UI and it worked just fine (I even then signed in with the new password). Could this be specific to the e2e test environment?

**Comment by webteckie** [comment]
@JedWatson I just realized the test is negative.  Thus, you need to enter mismatched passwords, in which case you'll get a 500 error.  Is that intentional?

**Comment by JedWatson** [comment]
@webteckie that makes sense. I am pretty sure this got fixed by #3419

**Comment by webteckie** [comment]
@JedWatson according to travis the e2e test failed on that push as well:  https://travis-ci.org/keystonejs/keystone/jobs/155064812

So it seems that didn't fix it :=)

**Comment by jstockwin** [comment]
@webteckie I'm just refactoring the password field and this seems to be working fine now. I'll enable the test along with everything else.

**Comment by jstockwin** [comment]
@webteckie Can you try this again and see if it's fixed, and close this if it is? Pretty sure it's all okay.

**Comment by webteckie** [comment]
@jstockwin yeah, seems fixed now.
