### ISSUE TITLE
[4-beta.3] Creating a new item often fails. 

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3545]
### Steps to reproduce the behavior

Start the test server. Add a new item. Go back to the list view. Delete the item from the list view. Now try and add another item.

### Expected behavior

A new item is added. 

### Actual behavior

A flash error message simply saying "Unknown error" appears. To fix this you have to refresh the page. 
In the console, we get: 
```
Error thrown for request: /keystone/api/booleans/create
SyntaxError: Unexpected token -
    at parse (D:\Documents\Development\GitHub\keystone\node_modules\body-parser\lib\types\json.js:83:15)
    at D:\Documents\Development\GitHub\keystone\node_modules\body-parser\lib\read.js:116:18
    at invokeCallback (D:\Documents\Development\GitHub\keystone\node_modules\raw-body\index.js:262:16)
    at done (D:\Documents\Development\GitHub\keystone\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (D:\Documents\Development\GitHub\keystone\node_modules\raw-body\index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by stuartforster** [comment]
I've also noticed this. I _think_ the unexpected token is the start of what looks to be a boundary segment in multi part form data.

**Comment by promethe42** [comment]
:+1:

**Comment by benkroeger** [comment]
noticed the same thing (also in .beta.2). this happens when`post`ing a form object with `xhr`... and somehow the content-type header is set to `application/json`.
In `express`, this triggers the `json` `body-parser`, which fails due to unexpected `-` char.

als happens when modifying an item (not only on creation)

**Comment by jstockwin** [comment]
@JedWatson / @mxstbr Do we simply need to update the `xhr` request to use `content-type: multipart/formdata`, or will that break other things?

**Comment by benkroeger** [comment]
@jstockwin most of the times, the `content-type` header is set correctly. we'd need to figure out why and when it sets `application/json`. as of today, I can't reliably reproduce this issue. it just happens every now and then (using Chrome 53.0.2785.116)

**Comment by benkroeger** [comment]
ok, found it.

1.  when deleting an item, keystone passes `Keystone.csrf.header` as `headers` to `xhr` and also set's `json` to `true`
2. since deleting an item is executet a a non `GET` nor `HEAD` request, `xhr` modifies the `headers` option to set `content-type: 'application/json'` (which is actually a modification of `Keystone.csrf.header`)
3. creating a new item immediately after deleting one, re-uses `Keystone.csrf.header` including `content-type: 'application/json'` although sending `FormData` --> backend can't parse request body

deleting items probably isn't the only cause for this issue.
My recommendation is, to always pass a clone of `Keystone.csrf.header` to `xhr`

**Comment by JedWatson** [comment]
Should be fixed now #3569 has been merged, thanks everyone for getting this sorted out!

**Comment by PTZ2002** [comment]
Hy, I have added this fix to Keystone version - 4.0.0 but this fix still not solves the problem with the unexpected token after deleting an item.
Any suggestion how could I force the content-type on post requests?
