### ISSUE TITLE
Admin UI continually compiling

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#7902]
On a Linux\WSL machine start a new project following the quick start guide: https://keystonejs.com/docs/walkthroughs/getting-started-with-create-keystone-app#quick-start

Run `yarn dev`

It should compile once, then as required by Next while editing code and browsing. 

- Confirmed it is working correctly on Windows.
- Confirmed it's not happening for prod builds. 
- It might be happening for CI running in production.
- I assume developers have tested this on Mac. 
- Confirmed it to be the AdminUI and not a NextJS problem.

Linux:

![image](https://user-images.githubusercontent.com/1320567/189265103-1e759a50-9188-4e9d-b432-ebd33478e9e8.png)

Windows: 

![image](https://user-images.githubusercontent.com/1320567/189265268-bcac1987-eb36-402b-9532-109eb2feb48c.png)

Next version: `v.12.3.0`

**Comment by cyanonoob** [comment]
Can confirm, having the same issue with a vanilla keystonekjs project. Running on manjaro with node 16.13.1 and 14.16.0.

**Comment by dcousens** [comment]
Can't reproduce this in my own Linux environment, maybe this is something to do with the filesystem used?

**Comment by christianpedersen** [comment]
This worked for me: Go to line 25 in auth.ts and change the sessionSecret to something else than the provided one. Not sure if it is related, but it stopped giving me compiled loop.

**Comment by jschuur** [comment]
> This worked for me: Go to line 25 in auth.ts and change the sessionSecret to something else than the provided one. Not sure if it is related, but it stopped giving me compiled loop.

Didn't seem to work for me.

I also ran into an endless loop after simply running `yarn create keystone-app keystone-test` and then `yarn dev` in the new dir.

I initially got 4.0.0 of @keystone-6/auth e.g., but even after upgrading to the latest versions, still the same problem.

**Comment by Faiyyaz** [comment]
I am also facing the same issue in macOS. I tried running the task-manager example too from the repository even in that code the issue persist.

**Comment by cyanonoob** [comment]
Is it possible that the autobuilder in dev mode is watching something get compiled, inadvertently triggering itself again?

**Comment by Shpackk** [comment]
> This worked for me: Go to line 25 in auth.ts and change the sessionSecret to something else than the provided one. Not sure if it is related, but it stopped giving me compiled loop.

Did not help . Facing same issue

**Comment by dcousens** [comment]
For those having problems, can you try changing your `next` version to `next@12.2.4`?
This problem should be resolved with our [recent switch to `esbuild`](https://github.com/keystonejs/keystone/pull/7809) but that is not released yet; and in the interim, reverting to the previous version of next should help.

Please reply back if that helps :pray:

**Comment by Ethras** [comment]
> For those having problems, can you try changing your `next` version to `next@12.2.4`? This problem should be resolved with our [recent switch to `esbuild`](https://github.com/keystonejs/keystone/pull/7809) but that is not released yet; and in the interim, reverting to the previous version of next should help.
> 
> Please reply back if that works for you 🙏

Facing the same issue but only when adding keystone to a turborepo. I tried with version "next@12.2.4" but no luck. Any way to try out with esbuild on main branch?

**Comment by jschuur** [comment]
> For those having problems, can you try changing your `next` version to `next@12.2.4`? 

Would this be done by just doing a `yarn add next@12.2.4`? This did not resolve the issue for me (even after I `rm -rf node_modules; yarn install` just in case.

Now I see a new error too (and it gets stuck in a loop as before):

```
event - compiled client and server successfully in 2.4s (1460 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build (client and server)...
event - compiled successfully in 44 ms (202 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 138 ms (1479 modules)
TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
    at Html (webpack-internal:///../../node_modules/@keystone-6/core/node_modules/next/dist/pages/_document.js:643:13)
    at renderWithHooks (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5661:16)
    at renderIndeterminateComponent (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5734:15)
    at renderElement (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6079:14)
    at finishClassComponent (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5691:3)
    at renderClassComponent (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5699:3)
    at renderElement (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/joostschuur/Code/Personal/_Tests/keystone-test/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
wait  - compiling...
event - compiled client and server successfully in 105 ms (1479 modules)
wait  - compiling...
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Failed to fetch update manifest Internal Server Error
    at http://localhost:3000/_next/static/chunks/fallback/webpack.js?ts=1662879424959:1176:37
wait  - compiling /init (client and server)...
event - compiled client and server successfully in 164 ms (1488 modules)
```

That error only turns up the first time I run `yarn dev` though. Subsequent times, I just get the looping compilation behaviour'.

Is there any way I can use `yarn create keystone-app` in the meantime and get it to lock in an older version, so I can create a new project?

**Comment by cyanonoob** [comment]
After trying:

`{
  "name": "keystone-app",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall"
  },
  "dependencies": {
    "@keystone-6/auth": "^4.0.0",
    "@keystone-6/core": "^2.1.0",
    "@keystone-6/fields-document": "^4.0.0",
    "typescript": "^4.7.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  },
  "overrides": {
    "next": "12.2.4"
  }
}`

I still have the same issue, also with trying rm -rf ./node_modules; yarn; yarn dev;

**Comment by flexdinesh** [comment]
Changing the next version to `12.2.4` using yarn `resolutions` fixes this issue.

Add this to your `package.json`. _Note: resolutions will only work with yarn_.

```
"resolutions": {
  "next": "12.2.4"
}
```

**Comment by MadeByMike** [comment]
Can confirm that running `yarn add next@12.2.4` then adding:

```
"resolutions": {
  "next": "12.2.4"
}
```

to the `package.json` seems to have worked for me.

**Comment by jordie23** [comment]
We've been seeing this issue for a while but as we weren't doing a lot of development on keystone itself we've been running a built (i.e. non-dev) version.  When we run `npm run dev` it has this problem. It's been around for a while but we figured it was because we're running behind on upgrading keystone. We are on version `1.1.1` of keystone and are about to try to update. I can see locally I had nextjs version `12.1.6` with this issue.

We're also using npm so looks like the resolutions fix won't work for us. 

We'll update keystone and see how we go, but did just want to add that we've been seeing the infinite compiling for quite a while now.

**Comment by yowlonglee** [comment]
For people using npm, run `npm install next@12.2.4` then adding:
```
"overrides": {
  "next": "12.2.4"
}
```
to `package.json` worked for me.

**Comment by dcousens** [comment]
If you are using `npm`, you [will need to install `graphql@^15.8.0` too](https://github.com/keystonejs/keystone/issues/7816).
You probably don't need the `overrides`.

See below for a dump of a log where I was able to reproduce this problem; and the steps I took to resolve it.
(tl;dr, use `npm install next@12.2.4 graphql@^15.8.0` to get started with `npm create keystone-app` until https://github.com/keystonejs/create-keystone-app/pull/350 is merged).

```
$ npm create keystone-app keystone-test-npm

✨ You're about to generate a project using Keystone 6 packages.

✔ Installed dependencies with yarn.

🎉  Keystone created a starter project in: keystone-test-npm

  To launch your app, run:

  - cd keystone-test-npm
  - yarn dev

  Next steps:

  - Read keystone-test-npm/README.md for additional getting started details.
  - Edit keystone-test-npm/keystone.ts to customize your app.
  - Open the Admin UI (​http://localhost:3000​)
  - Open the Graphql API (​http://localhost:3000/api/graphql​)
  - Read the docs (​https://next.keystonejs.com​)
  - Star Keystone on GitHub (​https://github.com/keystonejs/keystone​)

$ npm run dev
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /sandbox/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/sandbox/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2022-09-12T05_00_13_679Z-debug-0.log
$ cd keystone-test-npm/
$ npm run dev

> keystone-app@1.0.1 dev
> keystone dev

✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone.db" created at file:./keystone.db
✨ Your database is now in sync with your schema. Done in 387ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
event - compiled client and server successfully in 5.3s (1457 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build (client and server)...
event - compiled successfully in 94 ms (199 modules)
wait  - compiling...
event - compiled client and server successfully in 201 ms (1474 modules)
wait  - compiling...
event - compiled client and server successfully in 183 ms (1474 modules)
wait  - compiling...
event - compiled client and server successfully in 158 ms (1474 modules)
wait  - compiling...
event - compiled client and server successfully in 136 ms (1474 modules)
wait  - compiling...
event - compiled client and server successfully in 132 ms (1474 modules)
wait  - compiling...
event - compiled client and server successfully in 119 ms (1474 modules)
^C
$ npm install next@12.2.4

added 3 packages, removed 1 package, changed 8 packages, and audited 925 packages in 7s
... omitted

$ npm run dev

> keystone-app@1.0.1 dev
> keystone dev

✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
Error: Cannot use GraphQLInputObjectType "{ name: "IDFilter", description: undefined, extensions: {}, astNode: undefined, extensionASTNodes: [], _fields: [function bound defineInputFieldMap] }" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at ... omitted

> keystone-app@1.0.1 dev
> keystone dev

✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ The database is already in sync with the Prisma schema.
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
event - compiled client and server successfully in 5.3s (1456 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build...
event - compiled successfully in 102 ms (199 modules)

```

**Comment by cyanonoob** [comment]
Can confirm this works with next 12.2.4, can also confirm to have learned to use "resolutions" instead of "overrides" with yarn. Double thanks!

**Comment by pvaladez** [comment]
I needed to delete `node_modules/` and then reinstall packages with `yarn` after doing `yarn add next@12.2.4` and adding 
```
"resolutions": {
  "next": "12.2.4"
}
```
to `package.json`.

**Comment by linus-ha** [comment]
Would be great if someone could notify us here, when it's time to remove the "resolutions" from our package.json.

**Comment by MadeByMike** [comment]
@linus-ha you can't remove things from package.json only add ...forever 😜

**Comment by dcousens** [comment]
@linus-ha I intend

**Comment by dcousens** [comment]
@linus-ha my intention is to leave this issue open (and pinned as it is) until the next major release which will resolve these problems :+1:

**Comment by christiannaths** [comment]
Any ideas on how to work around this when running inside a yarn monorepo? `"resolutions"` doesn't seem to work (at either the packages/* level or the monorepo root), I think due to this bug: https://github.com/yarnpkg/yarn/issues/5039

Is there a known previous version I can downgrade to until this can be resolved here?

**Comment by naveenmatt** [comment]
> Changing the next version to `12.2.4` using yarn `resolutions` fixes this issue.
> 
> Add this to your `package.json`. _Note: resolutions will only work with yarn_.
> 
> ```
> "resolutions": {
>   "next": "12.2.4"
> }
> ```

This worked for me, thanks :)

**Comment by dcousens** [comment]
This has been resolved with the [newest major release](https://github.com/keystonejs/keystone/releases/tag/2022-10-19) :package:.

Please don't forget to remove your `resolutions` or `overrides` when upgrading.
Thanks for hanging in there everyone! :pray:

**Comment by ttbarnes** [comment]
I am still getting this issue unfortunately after upgrading to the latest package, getting this error with `npm ls graphql`

```cmd
invalid: "^16.3.0" from node_modules/graphql-upload
```


Node version: 16.4.2

Dependency versions: 

```js
"@graphql-tools/schema": "^9.0.9",
"@keystone-6/auth": "5.0.0",
"@keystone-6/core": "3.0.2",
"@keystone-6/fields-document": "5.0.1",
```
