### ISSUE TITLE
"keystone build" hangs indefinintely after update, no errors or logs indicating why

### ISSUE THREAD

**Issue by dfinton** [keystonejs/keystone#8412]
**Steps to reproduce**
After I update my keystone dependencies, `yarn build` hangs indefinitely on:
```
info  - Creating an optimized production build ...
```
`yarn dev` does complete and serves data, and I am able to login to the admin UI. It's only when trying to make a production build does it hang.

I checked for legacy issues matching what I was seeing on the various forums but nothing appears to be applicable to this circumstance. I'm not running out of processes or memory. I tried blowing away the existing build directory but nothing seems to work, and without an error message I don't have a lot to go on in terms of troubleshooting.

**What was expected**
Either for `yarn build` to complete without errors, or in the event of a failure, to report an error message

**Screenshot**
![keystone-hang](https://user-images.githubusercontent.com/348750/227724546-d64dbdb5-68c6-4752-ae18-451034c1660c.png)

**Contextual Information**
```
$ node --version
v18.15.0
```
package.json dependencies before update:
```
    "@keystone-6/auth": "^5.0.0",
    "@keystone-6/core": "^3.0.1",
    "@keystone-6/fields-document": "^5.0.0",
    "dotenv": "^16.0.3",
    "typescript": "^4.8.0"
```
after update:
```
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.1.0",
    "@keystone-6/fields-document": "^7.0.0",
    "dotenv": "^16.0.3",
    "typescript": "^4.8.0"
```

**Comment by dfinton** [comment]
Just wanted to leave an update: I am able to reproduce this issue by creating a brand new app with keystone-create-app. Even with an unmodified app, the build process hangs.
```
$ yarn create keystone-app surazal-net-cms
yarn create v1.22.19
...
Done in 33.24s.
$ cd surazal-net-cms
$ yarn dev
yarn run v1.22.19
$ keystone dev
...
event - compiled client and server successfully in 4.7s (1699 modules)
✅ Admin UI ready
^C
$ yarn build
yarn run v1.22.19
$ keystone build
...
info  - Creating an optimized production build ...
```
If I run `yarn build --no-ui` the process does not hang and completes successfully, but of course `yarn start` fails because it can't run the UI and aborts with an error.

**Comment by dfinton** [comment]
Further update: I tried this on my other platform to rule out an issue on my local development environment. The build also hangs on my Debian server:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
I also ran `npm cache clean --force` and ran everything from scratch to rule out a corrupted cache in both of my environments.

**Comment by dcousens** [comment]
@dfinton, @borisno2 and I noticed this bug late last week, and it's a result of using `next>13.2.2`.
In our recent pull request #8398, we fixed `next` to this version and are preparing a release in the next few days.

https://github.com/keystonejs/keystone/commit/1501892f88c144d7da2bfdc0b6480eb52baca5ce#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7R283

**Comment by borisno2** [comment]
Tested with the the following version of Next
- `13.2.3` build works
- `13.2.4` build hangs as described
- [latest canary build](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.19) build works
So it is just with Next version `13.2.4` where the build is broken and should be resolved in `13.2.5`

**Comment by AllanFerencz** [comment]
@borisno2 Looks like Next is on `13.3.0` now.

I still have the hanging build issue

**Comment by dcousens** [comment]
@AllanFerencz can you help with a reproduction?

**Comment by AllanFerencz** [comment]
Sure, It's reproducible with the current version of Keystone 6. 

1. Make a new project
2. `yarn`
3. `yarn build` - Hanging happens here

The latest version of `Next` in the `package.json` is pointing to version `13.2.2`

**Comment by borisno2** [comment]
Hi @AllanFerencz 
I am unable to replicate. I am doing the following
1. `yarn create keystone-app`
2. `cd` into directory
3. `yarn build`
Build happens as expected, if I use `yarn why next` I can see that it is installing `next@13.3.0`. 

Are you using `yarn create keystone-app` to make a new project or another method?

**Comment by borisno2** [comment]
Great, I'll close this issue now then. Thanks for letting us know
