### ISSUE TITLE
Admin relationship only showing 10 relations

### ISSUE THREAD

**Issue by stonean** [keystonejs/keystone#889]
I've been looking, but can't find an answer to this problem.

I have a relation defined as:

`program: { type: Types.Relationship, ref: 'Program', required: true, initial: false},`

I have 13 Programs, but only 10 are given as options and I can't find out why it's limiting the results in the drop down.

I'm using the master branch.

**Comment by JedWatson** [comment]
Sounds like this may be a bug with the options loading in the Relationship field, I'll check it out

**Comment by stonean** [comment]
Thanks for looking into this

**Comment by JedWatson** [comment]
I corrected some logic in the way result sets are handled by the relationship field, this is fixed now.

**Comment by stonean** [comment]
Thank you @JedWatson

**Comment by snawbel** [comment]
Hmm, I'm still seeing this in 0.3.1. Was this added to the release?

**Comment by JedWatson** [comment]
@snawbel it was, I'll check it again now.

**Comment by JedWatson** [comment]
There was a bug preventing *more* than ten from ever being loaded... that's been fixed, but it still doesn't indicate when there are more available. I've opened a new issue for that.

**Comment by snawbel** [comment]
Thanks for looking into it.
