### ISSUE TITLE
"Your GraphQL schema is not up to date"

### ISSUE THREAD

**Issue by Kisielec** [keystonejs/keystone#9304]
**Steps to reproduce:**
1. use command npm create keystone-app@latest or npx create-keystone-app@latest

**Description of problem:**
npm is returning an error "Your GraphQL schema is not up to date" all the time when I'm trying install Keystone 6, with create-keystone-app@10.0.0

**Error log:**
```
✖ Failed to install with npm.
Error: Command failed with exit code 1: npm install
Your GraphQL schema is not up to date
npm ERR! code 1
npm ERR! path C:\Users\krzys\Desktop\upforcewebsitebackend
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c keystone build --no-ui --frozen

npm ERR! A complete log of this run can be found in: C:\Users\krzys\AppData\Local\npm-cache\_logs\2024-08-24T16_33_49_678Z-debug-0.log

> keystone-app@1.0.3 postinstall
> keystone build --no-ui --frozen

    at makeError (C:\Users\krzys\AppData\Local\npm-cache\_npx\8f60d7ad6d9e085e\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\krzys\AppData\Local\npm-cache\_npx\8f60d7ad6d9e085e\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/krzys/AppData/Local/npm-cache/_npx/8f60d7ad6d9e085e/node_modules/create-keystone-app/dist/create-keystone-app.esm.js:89:5 {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> keystone-app@1.0.3 postinstall\n> keystone build --no-ui --frozen\n',
  stderr: 'Your GraphQL schema is not up to date\n' +
    'npm ERR! code 1\n' +
    'npm ERR! path C:\\Users\\krzys\\Desktop\\upforcewebsitebackend\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command C:\\Windows\\system32\\cmd.exe /d /s /c keystone build --no-ui --frozen\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: C:\\Users\\krzys\\AppData\\Local\\npm-cache\\_logs\\2024-08-24T16_33_49_678Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Test platform:**
Operating system: Windows 11 23H2, Manjaro 24.0.6 x64
NodeJS version: 21.7.3 , 20.14.0 , 18.20.4

**Comment by iamandrewluca** [comment]
This was fixed in https://github.com/keystonejs/keystone/pull/9275, it needs a release.

**Comment by dcousens** [comment]
Should be resolved in https://github.com/keystonejs/keystone/releases/tag/2024-08-28, please update and re-open this issue if the problem continues

**Comment by cheryl-c-tirerack** [comment]
Problem still exists.
Steps
clone repo @ said tag OR latest
step into the examples/framework-nextjs-app-directory folder
npm i --legacy-peer-deps

install fails with
> postinstall
> keystone postinstall

Your GraphQL schema is not up to date

**Comment by unrevised6419** [comment]
The issue you reported seems to be a different issue.
The current one is when you create a project from scratch with `create-keystone-app`

The projects inside `examples` is not guaranteed that all of them have the schemas synchronized.
You might need to do that manually until it will get fixed. PRs are welcome for that.
